### ISSUE TITLE
Support recursive reports

### ISSUE THREAD

**Issue by connor4312** [wgliang/goreporter#4]
I wanted to try this out on a project with multiple modules. It doesn't seem to support it, either reporting on the top-level `./` path or the Go-style `./...`

```
➜  project git:(v2) goreporter -p ./ -d ./-t ../../wgliang/goreporter/templates/template.html
[Apollo]2017/04/06 10:44:46 There are no packages that are excepted, review all items of the package
[Apollo]2017/04/06 10:44:46 start code quality assessment...
[Apollo]2017/04/06 10:44:46 computing cyclo...
[Apollo]2017/04/06 10:44:46 running unit test...
[Apollo]2017/04/06 10:44:46 simpling code...
[Apollo]2017/04/06 10:44:46 simpled code!
[Apollo]2017/04/06 10:44:46 checking copy code...
[Apollo]2017/04/06 10:44:46 running staticscan...
[Apollo]2017/04/06 10:44:46 creating depend graph...
[Apollo]2017/04/06 10:44:46 checking dead code...
[Apollo]2017/04/06 10:44:46 checking spell error...
[Apollo]2017/04/06 10:44:46 getting import packages...
[Apollo]2017/04/06 10:44:46 checked dead code
[Apollo]2017/04/06 10:44:46 failed to import ./: no buildable Go source files in /Users/copeet/go/src/github.com/WatchBeam/project

➜  project git:(v2) goreporter -p ./... -d ./-t ../../wgliang/goreporter/templates/template.html
[Apollo]2017/04/06 10:44:57 There are no packages that are excepted, review all items of the package
[Apollo]2017/04/06 10:44:57 start code quality assessment...
[Apollo]2017/04/06 10:44:57 lstat ./...: no such file or directory
[Apollo]2017/04/06 10:44:57 computing cyclo...
[Apollo]2017/04/06 10:44:57 lstat ./...: no such file or directory
[Apollo]2017/04/06 10:44:57 simpling code...
[Apollo]2017/04/06 10:44:57 simpled code!
[Apollo]2017/04/06 10:44:57 checking copy code...
[Apollo]2017/04/06 10:44:57 running staticscan...
[Apollo]2017/04/06 10:44:57 creating depend graph...
[Apollo]2017/04/06 10:44:57 checking dead code...
[Apollo]2017/04/06 10:44:57 checking spell error...
[Apollo]2017/04/06 10:44:57 getting import packages...
[Apollo]2017/04/06 10:44:57 cyclo over!
[Apollo]2017/04/06 10:44:57 running unit test...
[Apollo]2017/04/06 10:44:57 unit test over!
panic: lstat ./...: no such file or directory

goroutine 18 [running]:
panic(0x4ad180, 0xc4201003f0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/wgliang/goreporter/linters/copycheck.crawlPaths.func1(0xc42010c1a0, 0x1, 0x1, 0xc420240000, 0x56d672, 0x8)
	/Users/copeet/go/src/github.com/wgliang/goreporter/linters/copycheck/copycheck.go:97 +0x1fd
created by github.com/wgliang/goreporter/linters/copycheck.crawlPaths
	/Users/copeet/go/src/github.com/wgliang/goreporter/linters/copycheck/copycheck.go:119 +0x93
```

**Comment by wgliang** [comment]
I am sorry,it not support recursive reports. It only analyzes compiled items.

**Comment by connor4312** [comment]
Ah well 😕  Thanks for the quick response
