### ISSUE TITLE
Slice bounds out of range

### ISSUE THREAD

**Issue by bassu** [wgliang/goreporter#5]
With HEAD and all previous versions, there are panics.

Here's a possible stack trace:

```
 ./goreporter -d . -p . -t templates/template.html
[Apollo]2017/04/07 04:48:38 There are no packages that are excepted, review all items of the package
[Apollo]2017/04/07 04:48:38 start code quality assessment...
[Apollo]2017/04/07 04:48:38 computing cyclo...
[Apollo]2017/04/07 04:48:38 running unit test...
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.DirList.func1(0xc42025a9d0, 0x9, 0x17aee20, 0xc4202aad00, 0x0, 0x0, 0x0, 0x0)
	/Users/foo/Downloads/goreporter/utils.go:54 +0x219
path/filepath.walk(0xc42025a9d0, 0x9, 0x17aee20, 0xc4202aad00, 0xc42026f3b0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8/libexec/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0x7fff5fbff8cd, 0x1, 0x17aee20, 0xc420286a90, 0xc42026f3b0, 0x0, 0x30)
	/usr/local/Cellar/go/1.8/libexec/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0x7fff5fbff8cd, 0x1, 0xc42026f3b0, 0x0, 0xc42026f380)
	/usr/local/Cellar/go/1.8/libexec/src/path/filepath/path.go:398 +0x14c
main.DirList(0x7fff5fbff8cd, 0x1, 0x15683b2, 0x3, 0x0, 0x0, 0xc42001bf50, 0x0, 0x0)
```

**Comment by bassu** [comment]
@wgliang Looks like there is a typo at 40 in main.go.
Perhaps you meant `err != nil` instead of `err == nil`.

```
$ ag -A 2 -B 2 'project path is invalid'
main.go
41-		_, err := os.Stat(*project)
42-		if err == nil {
43:			log.Fatal("project path is invalid")
44-		}
45-	}
```

**Comment by wgliang** [comment]
Sorry, this is my negligence.
When I push it finish, I regret it.
